npx @stackblitz/cli@latest --create --project-name single-component-runner --description "A simple setup to run code generated by AI into a single React file on your local system."
npx @stackblitz/cli@latest --push
